// Package compiler implements an intentionally small, checked Go-to-C frontend.
package compiler

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/parser"
	"go/token"
	"go/types"
	"sort"
	"strconv"
	"strings"
)

const prelude = `// Generated by gosvm. Do not edit.
typedef unsigned char u8;
typedef unsigned int u32;
typedef unsigned long long u64;
typedef long long i64;
typedef _Bool boolean;
typedef struct { u8 *ptr; i64 len; } slice;
#ifdef GOSVM_SBF_V3
// Solana static syscall hash for abort (Murmur3 of "abort").
static __attribute__((noreturn)) void gosvm_abort(void) {
    ((void (*)(void))0xb6fc1a11ULL)();
    __builtin_unreachable();
}
#define abort gosvm_abort
#else
extern void abort(void) __attribute__((noreturn));
#endif
static u8 *at(slice s, u64 i) { if (i >= (u64)s.len) abort(); return s.ptr+i; }
`

type generator struct {
	fset *token.FileSet
	info *types.Info
	bytes.Buffer
	names map[types.Object]string
	next  int
}

// Source is a Go file in a single on-chain package.
type Source struct {
	Name string
	Data []byte
}

// Compile accepts one source file with a legacy byte-slice or SDK Context entrypoint.
// Unsupported constructs return source-located errors, never a best-effort translation.
func Compile(filename string, source []byte) ([]byte, error) {
	return CompileSources([]Source{{filename, source}})
}

// CompileSources checks a whole package. File order never affects generated output.
func CompileSources(sources []Source) (out []byte, err error) {
	g := &generator{fset: token.NewFileSet(), names: map[types.Object]string{}, info: &types.Info{
		Types: map[ast.Expr]types.TypeAndValue{}, Defs: map[*ast.Ident]types.Object{}, Uses: map[*ast.Ident]types.Object{},
	}}
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(compileError); ok {
				out, err = nil, e
			} else {
				panic(r)
			}
		}
	}()
	sources = append([]Source(nil), sources...)
	sort.Slice(sources, func(i, j int) bool { return sources[i].Name < sources[j].Name })
	files := []*ast.File{}
	decls := []ast.Decl{}
	hasImports := false
	for _, source := range sources {
		f, e := parser.ParseFile(g.fset, source.Name, source.Data, 0)
		if e != nil {
			return nil, e
		}
		files = append(files, f)
		decls = append(decls, f.Decls...)
		for _, im := range f.Imports {
			path, _ := strconv.Unquote(im.Path.Value)
			if path != "gosvm/solana" || im.Name != nil && (im.Name.Name == "." || im.Name.Name == "_") {
				g.fail(im, "only named gosvm/solana imports supported")
			}
			hasImports = true
		}
	}
	conf := types.Config{Sizes: &types.StdSizes{WordSize: 8, MaxAlign: 8}, Importer: &sdkImporter{}}
	pkg, err := conf.Check("program", g.fset, files, g.info)
	if err != nil {
		return nil, err
	}
	entry, ok := pkg.Scope().Lookup("Process").(*types.Func)
	byteSlice := types.NewSlice(types.Typ[types.Uint8])
	expected := types.NewSignatureType(nil, nil, nil,
		types.NewTuple(types.NewVar(0, nil, "", byteSlice), types.NewVar(0, nil, "", byteSlice)),
		types.NewTuple(types.NewVar(0, nil, "", types.Typ[types.Uint64])), false)
	contextEntry := false
	if ok {
		sig := entry.Type().(*types.Signature)
		contextEntry = sig.Params().Len() == 1 && isContext(sig.Params().At(0).Type()) && sig.Results().Len() == 1 && types.Identical(sig.Results().At(0).Type(), types.Typ[types.Uint64]) && !sig.Variadic()
	}
	if !ok || !types.Identical(entry.Type(), expected) && !contextEntry {
		return nil, fmt.Errorf("require Process([]byte, []byte) uint64 or Process(solana.Context) uint64")
	}
	// Reject recursion: this experiment has no stack-growth runtime.
	funcs := map[types.Object]*ast.FuncDecl{}
	for _, d := range decls {
		if fn, ok := d.(*ast.FuncDecl); ok {
			if fn.Body == nil {
				g.fail(fn, "bodyless functions are unsupported")
			}
			funcs[g.info.Defs[fn.Name]] = fn
		}
	}
	visited, active := map[types.Object]bool{}, map[types.Object]bool{}
	var visit func(types.Object)
	visit = func(o types.Object) {
		if active[o] {
			g.fail(funcs[o], "recursion is not supported")
		}
		if visited[o] {
			return
		}
		active[o] = true
		ast.Inspect(funcs[o].Body, func(n ast.Node) bool {
			if c, ok := n.(*ast.CallExpr); ok {
				if id, ok := c.Fun.(*ast.Ident); ok {
					if target := g.info.Uses[id]; funcs[target] != nil {
						visit(target)
					}
				}
			}
			return true
		})
		active[o], visited[o] = false, true
	}
	for o := range funcs {
		visit(o)
	}
	g.WriteString(prelude)
	if hasImports {
		g.WriteString(solanaRuntime)
	}
	// Define value structs before function prototypes, in dependency order.
	emitted := map[types.Type]bool{}
	var emitType func(ast.Node, types.Type)
	emitType = func(node ast.Node, t types.Type) {
		named, ok := t.(*types.Named)
		if !ok {
			g.fail(node, "only named scalar and value struct types supported")
		}
		if named.TypeParams().Len() != 0 {
			g.fail(node, "generic types unsupported")
		}
		if emitted[t] {
			return
		}
		emitted[t] = true
		st, ok := t.Underlying().(*types.Struct)
		if !ok {
			g.variable(node, t)
			return
		}
		for i := 0; i < st.NumFields(); i++ {
			f := st.Field(i)
			if f.Embedded() || isContext(f.Type()) {
				g.fail(node, "embedded and Context fields unsupported")
			}
			if _, ok := f.Type().Underlying().(*types.Struct); ok {
				emitType(node, f.Type())
			} else {
				if _, ok := f.Type().Underlying().(*types.Basic); !ok {
					g.fail(node, "struct fields must be unsigned scalars, bools, or value structs")
				}
				g.variable(node, f.Type())
			}
		}
		g.line("typedef struct {")
		// C11 has no empty structs; Go's zero-sized value has no observable layout here.
		if st.NumFields() == 0 {
			g.line("u8 unused;")
		}
		for i := 0; i < st.NumFields(); i++ {
			f := st.Field(i)
			g.line("%s %s;", g.variable(node, f.Type()), g.name(f))
		}
		g.line("} %s;", g.name(named.Obj()))
	}
	for _, d := range decls {
		if gen, ok := d.(*ast.GenDecl); ok && gen.Tok == token.TYPE {
			for _, sp := range gen.Specs {
				ts := sp.(*ast.TypeSpec)
				if ts.Assign.IsValid() {
					g.fail(ts, "type aliases unsupported")
				}
				emitType(ts, g.info.Defs[ts.Name].Type())
			}
		}
	}
	for _, d := range decls {
		switch d := d.(type) {
		case *ast.FuncDecl:
			g.WriteString(g.signature(d) + ";\n")
		case *ast.GenDecl:
			if d.Tok == token.IMPORT || d.Tok == token.TYPE {
				continue
			}
			if d.Tok != token.CONST {
				g.fail(d, "only functions and constants are supported at package scope")
			}
		default:
			g.fail(d, "unsupported declaration")
		}
	}
	for _, d := range decls {
		if fn, ok := d.(*ast.FuncDecl); ok {
			g.WriteString(g.signature(fn))
			g.block(fn.Body)
		}
	}
	if contextEntry {
		g.WriteString("\n#define GOSVM_CONTEXT_ENTRY 1\n")
		g.WriteString(accountsABI)
	}
	return g.Bytes(), nil
}

type compileError string

func (e compileError) Error() string { return string(e) }
func (g *generator) fail(n ast.Node, format string, args ...any) {
	panic(compileError(fmt.Sprintf("%s: %s", g.fset.Position(n.Pos()), fmt.Sprintf(format, args...))))
}
func (g *generator) line(format string, args ...any) { fmt.Fprintf(&g.Buffer, format+"\n", args...) }
func (g *generator) name(o types.Object) string {
	if o.Name() == "Process" && o.Parent() != nil && o.Parent().Parent() == types.Universe {
		return "go_Process"
	}
	if s := g.names[o]; s != "" {
		return s
	}
	g.next++
	s := fmt.Sprintf("v%d", g.next)
	g.names[o] = s
	return s
}
func (g *generator) ctype(n ast.Node, t types.Type) string {
	if isContext(t) {
		return "Context *"
	}
	if s, ok := t.(*types.Slice); ok && types.Identical(s.Elem(), types.Typ[types.Uint8]) {
		return "slice"
	}
	if n, ok := t.(*types.Named); ok {
		if _, ok := n.Underlying().(*types.Struct); ok {
			return g.name(n.Obj())
		}
	}
	if b, ok := t.Underlying().(*types.Basic); ok {
		switch b.Kind() {
		case types.Uint8:
			return "u8"
		case types.Uint32:
			return "u32"
		case types.Uint64, types.UntypedInt:
			return "u64"
		case types.Bool, types.UntypedBool:
			return "boolean"
		case types.Int:
			return "i64" // len only; signed variables/arithmetic rejected below.
		}
	}
	g.fail(n, "unsupported type %s", t)
	return ""
}
func (g *generator) variable(n ast.Node, t types.Type) string {
	if types.Identical(t.Underlying(), types.Typ[types.Int]) {
		g.fail(n, "use explicitly typed unsigned integers; int variables are unsupported")
	}
	return g.ctype(n, t)
}
func (g *generator) signature(fn *ast.FuncDecl) string {
	if fn.Name.Name == "init" {
		g.fail(fn, "init functions are unsupported")
	}
	if fn.Recv != nil || fn.Type.TypeParams != nil || fn.Body == nil {
		g.fail(fn, "methods, generics, and bodyless functions are unsupported")
	}
	sig := g.info.Defs[fn.Name].Type().(*types.Signature)
	if sig.Variadic() || sig.Results().Len() > 1 {
		g.fail(fn, "variadics and multiple results are unsupported")
	}
	ret := "void"
	if sig.Results().Len() == 1 {
		if sig.Results().At(0).Name() != "" {
			g.fail(fn, "named results are unsupported")
		}
		ret = g.variable(fn, sig.Results().At(0).Type())
	}
	args := []string{}
	for i := 0; i < sig.Params().Len(); i++ {
		p := sig.Params().At(i)
		args = append(args, g.variable(fn, p.Type())+" "+g.name(p))
	}
	if len(args) == 0 {
		args = append(args, "void")
	}
	return "static " + ret + " " + g.name(g.info.Defs[fn.Name]) + "(" + strings.Join(args, ",") + ")"
}
func (g *generator) temp(n ast.Node, t types.Type, value string) string {
	g.next++
	name := fmt.Sprintf("t%d", g.next)
	g.line("%s %s = %s;", g.ctype(n, t), name, value)
	return name
}
func (g *generator) expr(e ast.Expr) string {
	tv := g.info.Types[e]
	if tv.Value != nil {
		g.ctype(e, tv.Type)
		if tv.Value.Kind() == constant.Bool {
			if constant.BoolVal(tv.Value) {
				return "1"
			}
			return "0"
		}
		v, ok := constant.Uint64Val(tv.Value)
		if !ok {
			g.fail(e, "constant is outside uint64")
		}
		return fmt.Sprintf("%dULL", v)
	}
	switch e := e.(type) {
	case *ast.ParenExpr:
		return g.expr(e.X)
	case *ast.Ident:
		o := g.info.Uses[e]
		if _, ok := o.(*types.Var); !ok {
			g.fail(e, "unsupported identifier")
		}
		return g.temp(e, tv.Type, g.name(o))
	case *ast.CompositeLit:
		if isContext(tv.Type) {
			g.fail(e, "Context literals unsupported")
		}
		st, ok := tv.Type.Underlying().(*types.Struct)
		if !ok {
			g.fail(e, "only value struct literals supported")
		}
		r := g.temp(e, tv.Type, "{0}")
		for i, elt := range e.Elts {
			field := i
			value := elt
			if kv, ok := elt.(*ast.KeyValueExpr); ok {
				value = kv.Value
				field = -1
				id := kv.Key.(*ast.Ident)
				for j := 0; j < st.NumFields(); j++ {
					if st.Field(j).Name() == id.Name {
						field = j
						break
					}
				}
			}
			v := g.expr(value)
			g.line("%s.%s = %s;", r, g.name(st.Field(field)), v)
		}
		return r
	case *ast.SelectorExpr:
		if isContext(g.info.Types[e.X].Type) {
			g.fail(e, "Context fields are opaque")
		}
		field, ok := g.info.Uses[e.Sel].(*types.Var)
		if !ok || !field.IsField() {
			g.fail(e, "only value struct fields supported")
		}
		x := g.expr(e.X)
		return g.temp(e, tv.Type, x+"."+g.name(field))
	case *ast.IndexExpr:
		x, i := g.expr(e.X), g.expr(e.Index)
		return g.temp(e, tv.Type, fmt.Sprintf("*at(%s,%s)", x, i))
	case *ast.BinaryExpr:
		if _, ok := g.info.Types[e.X].Type.Underlying().(*types.Struct); ok {
			g.fail(e, "struct comparisons unsupported; compare fields explicitly")
		}
		x := g.expr(e.X)
		if e.Op == token.LAND || e.Op == token.LOR {
			r := g.temp(e, tv.Type, x)
			cond := r
			if e.Op == token.LOR {
				cond = "!" + r
			}
			g.line("if (%s) {", cond)
			y := g.expr(e.Y)
			g.line("%s = %s;\n}", r, y)
			return r
		}
		y := g.expr(e.Y)
		if e.Op == token.SHL || e.Op == token.SHR {
			bits := 64
			switch g.ctype(e, tv.Type) {
			case "u8":
				bits = 8
			case "u32":
				bits = 32
			case "u64":
			default:
				g.fail(e, "signed shifts unsupported")
			}
			return g.temp(e, tv.Type, fmt.Sprintf("%s >= %d ? 0 : ((u64)%s %s %s)", y, bits, x, e.Op, y))
		}
		if e.Op == token.QUO || e.Op == token.REM {
			g.line("if (%s == 0) abort();", y)
		}
		switch e.Op {
		case token.ADD, token.SUB, token.MUL, token.QUO, token.REM, token.AND, token.OR, token.XOR, token.AND_NOT:
			if b, ok := tv.Type.Underlying().(*types.Basic); !ok || b.Info()&types.IsUnsigned == 0 {
				g.fail(e, "signed arithmetic unsupported")
			}
		}
		op := e.Op.String()
		if e.Op == token.AND_NOT {
			op = "& ~"
		}
		// Widen first to avoid C's signed integer promotions for byte arithmetic.
		return g.temp(e, tv.Type, fmt.Sprintf("((u64)%s %s (u64)%s)", x, op, y))
	case *ast.UnaryExpr:
		x := g.expr(e.X)
		op := e.Op.String()
		switch e.Op {
		case token.NOT, token.ADD:
		case token.XOR:
			op = "~"
		case token.SUB:
			if b, ok := tv.Type.Underlying().(*types.Basic); !ok || b.Info()&types.IsUnsigned == 0 {
				g.fail(e, "signed negation unsupported")
			}
		default:
			g.fail(e, "unsupported unary operator")
		}
		return g.temp(e, tv.Type, fmt.Sprintf("(%s(u64)%s)", op, x))
	case *ast.CallExpr:
		if sel, ok := e.Fun.(*ast.SelectorExpr); ok {
			return g.importedCall(e, sel)
		}
		id, ok := e.Fun.(*ast.Ident)
		if !ok {
			g.fail(e, "only direct function calls supported")
		}
		args := []string{}
		for _, a := range e.Args {
			args = append(args, g.expr(a))
		}
		o := g.info.Uses[id]
		if _, ok := o.(*types.TypeName); ok {
			if _, ok := tv.Type.Underlying().(*types.Struct); ok {
				g.fail(e, "struct conversions unsupported; construct fields explicitly")
			}
			if len(args) != 1 {
				g.fail(e, "invalid conversion")
			}
			return g.temp(e, tv.Type, "("+g.variable(e, tv.Type)+")"+args[0])
		}
		if _, ok := o.(*types.Builtin); ok {
			if id.Name != "len" {
				g.fail(e, "only len builtin supported")
			}
			return g.temp(e, tv.Type, args[0]+".len")
		}
		if _, ok := o.(*types.Func); !ok {
			g.fail(e, "function values unsupported")
		}
		call := g.name(o) + "(" + strings.Join(args, ",") + ")"
		if tup, ok := tv.Type.(*types.Tuple); ok && tup.Len() == 0 {
			g.line("%s;", call)
			return ""
		}
		return g.temp(e, tv.Type, call)
	default:
		g.fail(e, "unsupported expression %T", e)
	}
	return ""
}
func (g *generator) block(b *ast.BlockStmt) {
	g.line("{")
	for _, s := range b.List {
		g.stmt(s)
	}
	g.line("}")
}
func (g *generator) stmt(s ast.Stmt) {
	switch s := s.(type) {
	case *ast.BlockStmt:
		g.block(s)
	case *ast.ReturnStmt:
		if len(s.Results) == 0 {
			g.line("return;")
		} else {
			v := g.expr(s.Results[0])
			g.line("return %s;", v)
		}
	case *ast.ExprStmt:
		g.expr(s.X)
	case *ast.AssignStmt:
		if len(s.Lhs) != 1 || len(s.Rhs) != 1 || (s.Tok != token.DEFINE && s.Tok != token.ASSIGN) {
			g.fail(s, "only single = and := assignments supported")
		}
		switch lhs := s.Lhs[0].(type) {
		case *ast.Ident:
			if lhs.Name == "_" {
				g.expr(s.Rhs[0])
				return
			}
			v := g.expr(s.Rhs[0])
			if s.Tok == token.DEFINE {
				o := g.info.Defs[lhs]
				g.line("%s %s = %s;", g.variable(lhs, o.Type()), g.name(o), v)
			} else {
				g.line("%s = %s;", g.name(g.info.Uses[lhs]), v)
			}
		case *ast.SelectorExpr:
			target := g.fieldTarget(lhs)
			v := g.expr(s.Rhs[0])
			g.line("%s = %s;", target, v)
		case *ast.IndexExpr:
			x, i := g.expr(lhs.X), g.expr(lhs.Index)
			v := g.expr(s.Rhs[0])
			g.line("*at(%s,%s) = %s;", x, i, v)
		default:
			g.fail(s, "unsupported assignment target")
		}
	case *ast.DeclStmt:
		d := s.Decl.(*ast.GenDecl)
		if d.Tok != token.VAR && d.Tok != token.CONST {
			g.fail(s, "unsupported local declaration")
		}
		if d.Tok == token.CONST {
			return
		}
		for _, sp := range d.Specs {
			v := sp.(*ast.ValueSpec)
			if len(v.Names) != 1 || len(v.Values) > 1 {
				g.fail(v, "only single variable declarations supported")
			}
			o := g.info.Defs[v.Names[0]]
			if isContext(o.Type()) && len(v.Values) == 0 {
				g.fail(v, "Context must come from the entrypoint, not a zero value")
			}
			rhs := "{0}"
			if len(v.Values) == 1 {
				rhs = g.expr(v.Values[0])
			}
			g.line("%s %s = %s;", g.variable(v, o.Type()), g.name(o), rhs)
		}
	case *ast.IfStmt:
		g.line("{")
		if s.Init != nil {
			g.stmt(s.Init)
		}
		c := g.expr(s.Cond)
		g.line("if (%s)", c)
		g.block(s.Body)
		if s.Else != nil {
			g.line("else")
			g.stmt(s.Else)
		}
		g.line("}")
	case *ast.ForStmt:
		g.line("{")
		if s.Init != nil {
			g.stmt(s.Init)
		}
		g.line("for (;;) {")
		if s.Cond != nil {
			c := g.expr(s.Cond)
			g.line("if (!(%s)) break;", c)
		}
		g.block(s.Body)
		if s.Post != nil {
			g.stmt(s.Post)
		}
		g.line("}\n}")
	case *ast.IncDecStmt:
		id, ok := s.X.(*ast.Ident)
		if !ok {
			g.fail(s, "only variable increment/decrement supported")
		}
		o := g.info.Uses[id]
		g.variable(s, o.Type())
		g.line("%s%s;", g.name(o), s.Tok)
	case *ast.BranchStmt:
		if s.Tok != token.BREAK || s.Label != nil {
			g.fail(s, "only unlabeled break supported")
		}
		g.line("break;")
	case *ast.EmptyStmt:
	default:
		g.fail(s, "unsupported statement %T", s)
	}
}

// Struct storage is a local variable or a chain of by-value fields; pointers,
// embedded fields, and Context inspection cannot enter this path.
func (g *generator) fieldTarget(e ast.Expr) string {
	switch e := e.(type) {
	case *ast.Ident:
		return g.name(g.info.Uses[e])
	case *ast.ParenExpr:
		return g.fieldTarget(e.X)
	case *ast.SelectorExpr:
		if isContext(g.info.Types[e.X].Type) {
			g.fail(e, "Context fields are opaque")
		}
		f, ok := g.info.Uses[e.Sel].(*types.Var)
		if !ok || !f.IsField() {
			g.fail(e, "unsupported field target")
		}
		return g.fieldTarget(e.X) + "." + g.name(f)
	default:
		g.fail(e, "field target must be a local value struct")
	}
	return ""
}
