// Code generated by gosvm generate. DO NOT EDIT.
package program

import "gosvm/solana"

func gosvmRead(b []byte, off uint64, size uint64) uint64 {
	v := uint64(0)
	for j := uint64(0); j < size; j++ {
		v = v | uint64(b[off+j])<<(j*8)
	}
	return v
}
func gosvmWrite(b []byte, off uint64, size uint64, v uint64) {
	for j := uint64(0); j < size; j++ {
		b[off+j] = byte(v >> (j * 8))
	}
}
func Process(c solana.Context) uint64 {
	if solana.Count(c) != 1 {
		return 6000
	}
	if !solana.Writable(c, 0) || solana.Executable(c, 0) {
		return 6001
	}
	owner := solana.Owner(c, 0)
	id := solana.ProgramID(c)
	if len(owner) != 32 || len(id) != 32 {
		return 6002
	}
	for j := uint64(0); j < 32; j = j + 8 {
		if gosvmRead(owner, j, 8) != gosvmRead(id, j, 8) {
			return 6002
		}
	}
	s := solana.Data(c, 0)
	ix := solana.Instruction(c)
	if len(s) != 32 {
		return 6003
	}
	if gosvmRead(s, 0, 8) != 13874821399147004193 {
		return 6003
	}
	if len(ix) != 24 {
		return 6004
	}
	if gosvmRead(ix, 0, 8) != 1704436820399925176 {
		return 6004
	}
	state := Pool{
		ReserveX:  uint64(gosvmRead(s, 8, 8)),
		ReserveY:  uint64(gosvmRead(s, 16, 8)),
		SwapCount: uint64(gosvmRead(s, 24, 8)),
	}
	args := SwapArgs{
		AmountIn:     uint64(gosvmRead(ix, 8, 8)),
		MinAmountOut: uint64(gosvmRead(ix, 16, 8)),
	}
	var result SwapResult
	result = Swap(state, args)
	if result.Code != 0 {
		return result.Code
	}
	gosvmWrite(s, 8, 8, uint64(result.State.ReserveX))
	gosvmWrite(s, 16, 8, uint64(result.State.ReserveY))
	gosvmWrite(s, 24, 8, uint64(result.State.SwapCount))
	return 0
}
