package project

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"go/types"
	"path/filepath"
	"sort"
	"strings"

	"gosvm/internal/compiler"
)

func generateMulti(dir string, c Config) error {
	m, err := resolveMulti(dir, c)
	if err != nil {
		return err
	}
	lock, err := m.checkedLock(dir)
	if err != nil {
		return err
	}
	adapter, err := m.adapter()
	if err != nil {
		return err
	}
	sources, _, err := schema2Sources(dir)
	if err != nil {
		return err
	}
	// Replace provisional declarations with the complete adapter, then perform
	// the compiler's language and borrowing checks before changing any artifact.
	program, err := compiler.ReadProgramWithSources(dir, append(sources, compiler.Source{Name: filepath.Join(dir, "zz_gosvm.go"), Data: adapter}))
	if err != nil {
		return err
	}
	if _, err = compiler.CompileProgram(program); err != nil {
		return err
	}
	client, err := m.client()
	if err != nil {
		return err
	}
	idl, err := json.MarshalIndent(struct {
		Format          string                   `json:"format"`
		Name            string                   `json:"name"`
		Accounts        []WireLayout             `json:"accounts"`
		Arguments       []WireLayout             `json:"arguments"`
		Instructions    []InstructionDeclaration `json:"instructions"`
		Errors          map[string]uint64        `json:"errors"`
		ValidationOrder []string                 `json:"validation_order"`
	}{"gosvm-2", c.Name, m.States, m.Arguments, c.Instructions, m.Errors, multiValidationOrder(c)}, "", "  ")
	if err != nil {
		return err
	}
	// All diagnostics precede publication. Preserve unchanged modification times.
	for _, artifact := range []struct {
		path string
		data []byte
	}{{"zz_gosvm.go", adapter}, {"client/zz_gosvm.go", client}, {"idl.json", append(idl, '\n')}, {"layouts.json", lock}} {
		if err := writeChanged(filepath.Join(dir, artifact.path), artifact.data); err != nil {
			return err
		}
	}
	return nil
}

func (m *multiModel) goSource(pkg, body string, host bool) ([]byte, error) {
	var code bytes.Buffer
	fmt.Fprintf(&code, "// Code generated by gosvm generate (schema 2). DO NOT EDIT.\npackage %s\nimport (\n", pkg)
	if host {
		fmt.Fprint(&code, "\"encoding/binary\"\n\"fmt\"\n")
	} else {
		fmt.Fprint(&code, "\"gosvm/solana\"\n")
	}
	paths := make([]string, 0, len(m.Imports))
	for path, alias := range m.Imports {
		if strings.Contains(body, alias+".") {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&code, "%s %q\n", m.Imports[path], path)
	}
	fmt.Fprintf(&code, ")\n%s", body)
	out, err := format.Source(code.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated %s: %w", pkg, err)
	}
	return out, nil
}

func (m *multiModel) bundles(out *bytes.Buffer) {
	fmt.Fprint(out, "type GosvmAccountRef struct { Index uint64; Key [32]byte }\n")
	for _, ix := range m.Config.Instructions {
		fmt.Fprintf(out, "type %s struct {\n", ix.Bundle)
		for _, a := range ix.Accounts {
			t := "GosvmAccountRef"
			if a.Kind == "state" {
				t = m.typeName(m.States[m.StateByName[a.Layout]].GoType)
			} else if a.Kind == "token" {
				t = m.Imports["gosvm/sdk/token"] + ".Account"
			}
			fmt.Fprintf(out, "%s %s\n", a.Name, t)
			if a.Ref != "" {
				fmt.Fprintf(out, "%s GosvmAccountRef\n", a.Ref)
			}
		}
		fmt.Fprint(out, "}\n")
	}
}

func (m *multiModel) adapter() ([]byte, error) {
	var out bytes.Buffer
	m.bundles(&out)
	fmt.Fprint(&out, `func gosvmRead(b []byte, off uint64, size uint64) uint64 { v:=uint64(0); for j:=uint64(0);j<size;j++ { v=v|uint64(b[off+j])<<(j*8) };return v }
func gosvmWrite(b []byte, off uint64, size uint64, v uint64) { for j:=uint64(0);j<size;j++ {b[off+j]=byte(v>>(j*8))} }
func gosvmKeysEqual(left []byte, right []byte) bool { if len(left)!=32 || len(right)!=32 { return false }; for j:=uint64(0);j<32;j++ { if left[j]!=right[j] { return false } }; return true }
func Process(c solana.Context) uint64 {
 ix:=solana.Instruction(c)
 if len(ix)<8 { return 6004 }
 switch gosvmRead(ix,0,8) {
`)
	for i, ix := range m.Config.Instructions {
		fmt.Fprintf(&out, "case %d: if len(ix)!=%d { return 6004 }; return gosvmExec%s(c)\n", discWord(m.Arguments[i].Discriminator), m.Arguments[i].Size, ix.Name)
	}
	fmt.Fprint(&out, "default: return 6004\n}\n}\n")
	for i, ix := range m.Config.Instructions {
		m.instructionAdapter(&out, ix, m.Arguments[i])
		for _, a := range ix.Accounts {
			if a.PDA != nil {
				m.pdaAdapter(&out, ix, a, m.Arguments[i])
			}
			if a.Init != nil {
				m.initAdapter(&out, ix, a, m.Arguments[i])
			}
		}
	}
	return m.goSource(m.Package, out.String(), false)
}

func (m *multiModel) instructionAdapter(out *bytes.Buffer, ix InstructionDeclaration, args WireLayout) {
	fmt.Fprintf(out, "func gosvmExec%s(c solana.Context) uint64 {\nif solana.Count(c)!=%d { return 6000 }\n", ix.Name, len(ix.Accounts))
	for j, a := range ix.Accounts {
		if a.Access == "write" {
			fmt.Fprintf(out, "if !solana.Writable(c,%d) { return 6001 }\n", j)
		}
		if a.Signer || a.Kind == "signer" {
			fmt.Fprintf(out, "if !solana.Signer(c,%d) { return 6001 }\n", j)
		}
		if a.Kind == "program" {
			fmt.Fprintf(out, "if !solana.Executable(c,%d) { return 6001 }\n", j)
		} else {
			fmt.Fprintf(out, "if solana.Executable(c,%d) { return 6001 }\n", j)
		}
	}
	needsID := false
	for _, a := range ix.Accounts {
		if a.Owner == "program_id" {
			needsID = true
		}
	}
	if needsID {
		fmt.Fprint(out, "id:=solana.ProgramID(c); if len(id)!=32 { return 6002 }\n")
	}
	for j, a := range ix.Accounts {
		fmt.Fprintf(out, "key%d:=solana.Key(c,%d); if len(key%d)!=32 { return 6005 }\n", j, j, j)
		if a.Address != "" {
			key, _ := hexKey(a.Address)
			for k, v := range key {
				fmt.Fprintf(out, "if key%d[%d]!=%d { return 6005 }\n", j, k, v)
			}
		}
		if a.Owner != "" && a.Init == nil {
			fmt.Fprintf(out, "owner%d:=solana.Owner(c,%d); if len(owner%d)!=32 { return 6002 }\n", j, j, j)
			if a.Owner == "program_id" {
				fmt.Fprintf(out, "if !gosvmKeysEqual(owner%d,id) { return 6002 }\n", j)
			} else {
				key, _ := hexKey(a.Owner)
				for k, v := range key {
					fmt.Fprintf(out, "if owner%d[%d]!=%d { return 6002 }\n", j, k, v)
				}
			}
		}
	}
	allowed := map[string]bool{}
	for _, p := range ix.Aliases {
		allowed[aliasKey(p.Left, p.Right)] = true
	}
	for j, a := range ix.Accounts {
		for k := j + 1; k < len(ix.Accounts); k++ {
			if !allowed[aliasKey(a.Name, ix.Accounts[k].Name)] {
				fmt.Fprintf(out, "if gosvmKeysEqual(key%d,key%d) { return 6006 }\n", j, k)
			}
		}
	}
	m.initTargets(out, ix)
	fmt.Fprintf(out, "var accounts %s\n", ix.Bundle)
	for j, a := range ix.Accounts {
		if a.Kind == "state" {
			if a.Init == nil {
				l := m.States[m.StateByName[a.Layout]]
				fmt.Fprintf(out, "state%d:=solana.Data(c,%d); if len(state%d)!=%d { return 6003 }; if gosvmRead(state%d,0,8)!=%d { return 6003 }\n", j, j, j, l.Size, j, discWord(l.Discriminator))
				m.codecFields(out, l.Fields, "accounts."+a.Name, fmt.Sprintf("state%d", j), false, false)
			}
		} else if a.Kind != "token" {
			fmt.Fprintf(out, "accounts.%s.Index=%d\nfor j:=uint64(0);j<32;j++ { accounts.%s.Key[j]=key%d[j] }\n", a.Name, j, a.Name, j)
		}
		if a.Ref != "" {
			fmt.Fprintf(out, "accounts.%s.Index=%d\nfor j:=uint64(0);j<32;j++ { accounts.%s.Key[j]=key%d[j] }\n", a.Ref, j, a.Ref, j)
		}
	}
	for j, a := range ix.Accounts {
		if a.Kind == "token" {
			alias := m.Imports["gosvm/sdk/token"]
			fmt.Fprintf(out, "tokenRef%d,tokenCode%d:=%s.Load(c,%d,%t);if tokenCode%d!=0 { return tokenCode%d };accounts.%s=tokenRef%d\n", j, j, alias, j, a.Access == "write", j, j, a.Name, j)
			used := false
			for _, rel := range ix.Relations {
				if strings.HasPrefix(rel.Field, a.Name+".") || strings.HasPrefix(rel.Equals, a.Name+".") {
					used = true
				}
			}
			if used {
				fmt.Fprintf(out, "tokenState%d,tokenReadCode%d:=%s.Read(c,tokenRef%d);if tokenReadCode%d!=0 { return tokenReadCode%d }\n", j, j, alias, j, j, j)
			}
		}
	}
	if relationArgs(ix) {
		m.argumentAdapter(out, args)
	}
	for _, rel := range ix.Relations {
		j := 0
		for k, a := range ix.Accounts {
			if a.Name == rel.Account {
				j = k
			}
		}
		_, field, _ := m.constraintField(ix, args.GoType, rel.Field, true)
		target := fmt.Sprintf("key%d", j)
		if rel.Equals != "" {
			_, target, _ = m.constraintField(ix, args.GoType, rel.Equals, true)
		}
		fmt.Fprintf(out, "for j:=uint64(0);j<32;j++ { if %s[j]!=%s[j] { return 6007 } }\n", field, target)
	}
	m.closeAuthorities(out, ix, args)
	if !relationArgs(ix) {
		m.argumentAdapter(out, args)
	}
	for _, a := range ix.Accounts {
		if a.PDA != nil {
			fmt.Fprintf(out, "if gosvmPDA_%s_%s(c,accounts,args)!=0 { return 6008 }\n", ix.Name, a.Name)
		}
	}
	if hasInit(Config{Instructions: []InstructionDeclaration{ix}}) {
		fmt.Fprint(out, "var initOwner [32]byte; for j:=uint64(0);j<32;j++ { initOwner[j]=id[j] }\n")
		for _, a := range ix.Accounts {
			if a.Init != nil {
				fmt.Fprintf(out, "initCode%s:=gosvmInit_%s_%s(c,accounts,args,initOwner);if initCode%s!=0 { return initCode%s }\n", a.Name, ix.Name, a.Name, a.Name, a.Name)
			}
		}
	}
	fmt.Fprintf(out, "updated, code := %s(c,accounts,args); if code!=0 { return code }\n", ix.Handler)
	for j, a := range ix.Accounts {
		if a.Close != nil {
			fmt.Fprintf(out, "closeCode%s:=solana.CloseAccount(c,%d,%d);if closeCode%s!=0 { return closeCode%s }\n", a.Name, j, accountIndex(ix, a.Close.To), a.Name, a.Name)
		}
	}
	// A readonly result is deliberately not serialized. Non-state references are
	// not serialized either, so they cannot overwrite token/CPI account changes.
	for j, a := range ix.Accounts {
		if a.Kind == "state" && a.Access == "write" && a.Close == nil {
			if instructionLifecycle(ix) {
				assign := "="
				if a.Init != nil {
					assign = ":="
				}
				l := m.States[m.StateByName[a.Layout]]
				fmt.Fprintf(out, "state%d%s solana.Data(c,%d); if len(state%d)!=%d { return 6003 };if !gosvmKeysEqual(solana.Owner(c,%d),id) { return 6002 }\n", j, assign, j, j, l.Size, j)
				if a.Init != nil {
					fmt.Fprintf(out, "gosvmWrite(state%d,0,8,%d)\n", j, discWord(l.Discriminator))
				} else {
					fmt.Fprintf(out, "if gosvmRead(state%d,0,8)!=%d { return 6003 }\n", j, discWord(l.Discriminator))
				}
			}
			m.codecFields(out, m.States[m.StateByName[a.Layout]].Fields, "updated."+a.Name, fmt.Sprintf("state%d", j), true, false)
		}
	}
	// Instructions with no writable state still need to consume the returned
	// bundle in ordinary Go; blank assignment is also supported by the compiler.
	fmt.Fprint(out, "_ = updated\nreturn 0\n}\n")
}

func (m *multiModel) argumentAdapter(out *bytes.Buffer, args WireLayout) {
	fmt.Fprintf(out, "ix:=solana.Instruction(c); var args %s\n", m.typeName(args.GoType))
	m.codecFields(out, args.Fields, "args", "ix", false, false)
	if len(args.Fields) == 0 {
		fmt.Fprint(out, "_ = ix\n")
	}
}

// codecFields emits accesses from the packed resolved model. Native clients and
// the on-chain adapter use the same offsets, but separate ordinary-Go operations.
func (m *multiModel) codecFields(out *bytes.Buffer, fields []WireField, value, buffer string, encode, host bool) {
	for _, f := range fields {
		path := value + "." + f.Name
		switch u := f.GoType.Underlying().(type) {
		case *types.Struct:
			m.codecFields(out, f.Fields, path, buffer, encode, host)
		case *types.Array:
			size := 0
			switch u.Elem().Underlying().(*types.Basic).Kind() {
			case types.Uint8:
				size = 1
			case types.Uint32:
				size = 4
			case types.Uint64:
				size = 8
			}
			fmt.Fprintf(out, "for j:=uint64(0);j<%d;j++ {\n", u.Len())
			m.codecScalar(out, path+"[j]", buffer, fmt.Sprintf("%d+j*%d", f.Offset, size), size, u.Elem(), encode, host)
			fmt.Fprint(out, "}\n")
		default:
			m.codecScalar(out, path, buffer, fmt.Sprint(f.Offset), f.Size, f.GoType, encode, host)
		}
	}
}

func (m *multiModel) codecScalar(out *bytes.Buffer, value, buffer, offset string, size int, t types.Type, encode, host bool) {
	if host {
		if encode {
			if size == 1 {
				fmt.Fprintf(out, "%s[%s]=byte(%s)\n", buffer, offset, value)
			} else {
				fmt.Fprintf(out, "binary.LittleEndian.PutUint%d(%s[%s:],uint%d(%s))\n", size*8, buffer, offset, size*8, value)
			}
		} else {
			read := fmt.Sprintf("%s[%s]", buffer, offset)
			if size != 1 {
				read = fmt.Sprintf("binary.LittleEndian.Uint%d(%s[%s:])", size*8, buffer, offset)
			}
			fmt.Fprintf(out, "%s=%s(%s)\n", value, m.typeName(t), read)
		}
	} else if encode {
		fmt.Fprintf(out, "gosvmWrite(%s,%s,%d,uint64(%s))\n", buffer, offset, size, value)
	} else {
		fmt.Fprintf(out, "%s=%s(gosvmRead(%s,%s,%d))\n", value, m.typeName(t), buffer, offset, size)
	}
}

func (m *multiModel) client() ([]byte, error) {
	var out bytes.Buffer
	all := append(append([]WireLayout(nil), m.States...), m.Arguments...)
	for _, l := range all {
		// Names include the wire category so an account and instruction can share
		// their public name without client symbol collisions.
		name := "Account" + l.Name
		if l.Kind == "instruction" {
			name = "Instruction" + l.Name
		}
		fmt.Fprintf(&out, "const %sSize = %d\nconst %sVersion uint32 = %d\nfunc Encode%s(v %s) []byte { b:=make([]byte,%d); binary.LittleEndian.PutUint64(b,%d)\n", name, l.Size, name, l.Version, name, m.typeName(l.GoType), l.Size, discWord(l.Discriminator))
		m.codecFields(&out, l.Fields, "v", "b", true, true)
		fmt.Fprint(&out, "return b\n}\n")
		fmt.Fprintf(&out, "func Decode%s(b []byte) (%s,error) { var v %s; if len(b)!=%d { return v,fmt.Errorf(\"invalid %s size\") }; if binary.LittleEndian.Uint64(b)!=%d { return v,fmt.Errorf(\"invalid %s discriminator/version\") }\n", name, m.typeName(l.GoType), m.typeName(l.GoType), l.Size, name, discWord(l.Discriminator), name)
		m.codecFields(&out, l.Fields, "v", "b", false, true)
		fmt.Fprint(&out, "return v,nil\n}\n")
	}
	return m.goSource("client", out.String(), true)
}
