package project

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"path/filepath"
	"strconv"
	"strings"

	"gosvm/internal/compiler"
)

type field struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Offset int    `json:"offset"`
	Size   int    `json:"size"`
}
type layout struct {
	Name          string  `json:"name"`
	Discriminator []int   `json:"discriminator"`
	Size          int     `json:"size"`
	Fields        []field `json:"fields"`
}

func discriminator(namespace, name string) []int {
	h := sha256.Sum256([]byte("gosvm:" + namespace + ":" + name))
	r := make([]int, 8)
	for i := range r {
		r[i] = int(h[i])
	}
	return r
}
func discWord(d []int) uint64 {
	var b [8]byte
	for i, v := range d {
		b[i] = byte(v)
	}
	return binary.LittleEndian.Uint64(b[:])
}

// Generate emits explicit, allocation-free codecs and a checked account adapter.
// The first binding format intentionally only supports flat unsigned wire fields.
func Generate(dir string) error {
	c, e := Load(dir)
	if e != nil {
		return e
	}
	sources, e := compiler.ReadSources(dir)
	if e != nil {
		return e
	}
	fs := token.NewFileSet()
	typesByName := map[string]*ast.TypeSpec{}
	packageName := ""
	errors := map[string]uint64{"AccountCount": 6000, "AccountFlags": 6001, "AccountOwner": 6002, "StateLayout": 6003, "InstructionLayout": 6004}
	for _, src := range sources {
		if filepath.Base(src.Name) == "zz_gosvm.go" {
			continue
		}
		f, e := parser.ParseFile(fs, src.Name, src.Data, 0)
		if e != nil {
			return e
		}
		if packageName != "" && packageName != f.Name.Name {
			return fmt.Errorf("%s: package mismatch", src.Name)
		}
		packageName = f.Name.Name
		for _, d := range f.Decls {
			if gen, ok := d.(*ast.GenDecl); ok {
				for _, sp := range gen.Specs {
					if ts, ok := sp.(*ast.TypeSpec); ok {
						typesByName[ts.Name.Name] = ts
					}
					if vs, ok := sp.(*ast.ValueSpec); ok && gen.Tok == token.CONST && len(vs.Names) == 1 && len(vs.Values) == 1 && strings.HasPrefix(vs.Names[0].Name, "Err") {
						if lit, ok := vs.Values[0].(*ast.BasicLit); ok {
							v, e := strconv.ParseUint(lit.Value, 0, 64)
							if e == nil {
								if v == 0 || v >= 6000 {
									return fmt.Errorf("%s: handler errors must be 1..5999", fs.Position(vs.Pos()))
								}
								errors[vs.Names[0].Name] = v
							}
						}
					}
				}
			}
		}
	}
	parseLayout := func(name, namespace string) (layout, error) {
		out := layout{Name: name, Discriminator: discriminator(namespace, name), Size: 8}
		ts := typesByName[name]
		if ts == nil {
			return out, fmt.Errorf("binding type %s not found", name)
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok || ts.Assign.IsValid() {
			return out, fmt.Errorf("%s: wire type must be a declared struct", fs.Position(ts.Pos()))
		}
		for _, f := range st.Fields.List {
			id, ok := f.Type.(*ast.Ident)
			if !ok {
				return out, fmt.Errorf("%s: wire fields require uint64, uint32, or byte", fs.Position(f.Pos()))
			}
			size := map[string]int{"uint64": 8, "uint32": 4, "byte": 1, "uint8": 1}[id.Name]
			if size == 0 || len(f.Names) == 0 || f.Tag != nil {
				return out, fmt.Errorf("%s: wire fields require explicit unsigned types, no embedding or tags", fs.Position(f.Pos()))
			}
			for _, n := range f.Names {
				if !identRE.MatchString(n.Name) {
					return out, fmt.Errorf("%s: wire fields must be exported", fs.Position(n.Pos()))
				}
				out.Fields = append(out.Fields, field{n.Name, id.Name, out.Size, size})
				out.Size += size
			}
		}
		if out.Size > 1024 {
			return out, fmt.Errorf("%s: first binding format caps encoded structs at 1024 bytes", name)
		}
		return out, nil
	}
	state, e := parseLayout(c.State, "account")
	if e != nil {
		return e
	}
	args, e := parseLayout(c.Instruction, "instruction")
	if e != nil {
		return e
	}
	var code bytes.Buffer
	fmt.Fprintf(&code, "// Code generated by gosvm generate. DO NOT EDIT.\npackage %s\nimport \"gosvm/solana\"\n", packageName)
	fmt.Fprint(&code, `func gosvmRead(b []byte, off uint64, size uint64) uint64 { v:=uint64(0); for j:=uint64(0);j<size;j++ { v=v|uint64(b[off+j])<<(j*8) };return v }
func gosvmWrite(b []byte, off uint64, size uint64, v uint64) { for j:=uint64(0);j<size;j++ {b[off+j]=byte(v>>(j*8))} }
func Process(c solana.Context) uint64 {
 if solana.Count(c)!=1 {return 6000}
 if !solana.Writable(c,0)||solana.Executable(c,0){return 6001}
 owner:=solana.Owner(c,0); id:=solana.ProgramID(c)
 if len(owner)!=32||len(id)!=32{return 6002}
 for j:=uint64(0);j<32;j=j+8 {if gosvmRead(owner,j,8)!=gosvmRead(id,j,8){return 6002}}
 s:=solana.Data(c,0); ix:=solana.Instruction(c)
`)
	fmt.Fprintf(&code, "if len(s)!=%d {return 6003}; if gosvmRead(s,0,8)!=%d {return 6003}\n", state.Size, discWord(state.Discriminator))
	fmt.Fprintf(&code, "if len(ix)!=%d {return 6004}; if gosvmRead(ix,0,8)!=%d {return 6004}\n", args.Size, discWord(args.Discriminator))
	for _, item := range []struct {
		l    layout
		v, b string
	}{{state, "state", "s"}, {args, "args", "ix"}} {
		fmt.Fprintf(&code, "%s:=%s{\n", item.v, item.l.Name)
		for _, f := range item.l.Fields {
			fmt.Fprintf(&code, "%s:%s(gosvmRead(%s,%d,%d)),\n", f.Name, f.Type, item.b, f.Offset, f.Size)
		}
		fmt.Fprint(&code, "}\n")
	}
	fmt.Fprintf(&code, "var result %s; result=%s(state,args)\nif result.Code!=0{return result.Code}\n", c.Result, c.Handler)
	for _, f := range state.Fields {
		fmt.Fprintf(&code, "gosvmWrite(s,%d,%d,uint64(result.State.%s))\n", f.Offset, f.Size, f.Name)
	}
	fmt.Fprint(&code, "return 0\n}\n")
	generated, e := format.Source(code.Bytes())
	if e != nil {
		return fmt.Errorf("generate entrypoint: %w", e)
	}
	// Validate before touching existing generated artifacts.
	var checked []compiler.Source
	for _, src := range sources {
		if filepath.Base(src.Name) != "zz_gosvm.go" {
			checked = append(checked, src)
		}
	}
	checked = append(checked, compiler.Source{Name: filepath.Join(dir, "zz_gosvm.go"), Data: generated})
	if _, e = compiler.CompileSources(checked); e != nil {
		return e
	}
	var client bytes.Buffer
	fmt.Fprintf(&client, "// Code generated by gosvm generate. DO NOT EDIT.\npackage client\nimport (\"encoding/binary\";\"fmt\"; program %q)\n", c.Module)
	for _, l := range []layout{state, args} {
		fmt.Fprintf(&client, "func Encode%s(v program.%s) []byte {b:=make([]byte,%d);binary.LittleEndian.PutUint64(b,%d)\n", l.Name, l.Name, l.Size, discWord(l.Discriminator))
		for _, f := range l.Fields {
			if f.Size == 1 {
				fmt.Fprintf(&client, "b[%d]=byte(v.%s)\n", f.Offset, f.Name)
			} else {
				fmt.Fprintf(&client, "binary.LittleEndian.PutUint%d(b[%d:],v.%s)\n", f.Size*8, f.Offset, f.Name)
			}
		}
		fmt.Fprint(&client, "return b}\n")
		fmt.Fprintf(&client, "func Decode%s(b []byte) (program.%s,error) {var v program.%s; if len(b)!=%d{return v,fmt.Errorf(\"invalid %s size\")};if binary.LittleEndian.Uint64(b)!=%d{return v,fmt.Errorf(\"invalid %s discriminator\")}\n", l.Name, l.Name, l.Name, l.Size, l.Name, discWord(l.Discriminator), l.Name)
		for _, f := range l.Fields {
			if f.Size == 1 {
				fmt.Fprintf(&client, "v.%s=b[%d]\n", f.Name, f.Offset)
			} else {
				fmt.Fprintf(&client, "v.%s=binary.LittleEndian.Uint%d(b[%d:])\n", f.Name, f.Size*8, f.Offset)
			}
		}
		fmt.Fprint(&client, "return v,nil}\n")
	}
	clientCode, e := format.Source(client.Bytes())
	if e != nil {
		return e
	}
	idl, e := json.MarshalIndent(map[string]any{"format": "gosvm-1", "name": c.Name, "account": state, "instruction": args, "handler": c.Handler, "errors": errors, "constraints": map[string]any{"account_count": 1, "writable": true, "executable": false, "owner": "program_id"}}, "", "  ")
	if e != nil {
		return e
	}
	for p, b := range map[string][]byte{"zz_gosvm.go": generated, "client/zz_gosvm.go": clientCode, "idl.json": append(idl, '\n')} {
		if e = writeChanged(filepath.Join(dir, p), b); e != nil {
			return e
		}
	}
	return nil
}
