// Code generated by gosvm generate (schema 2). DO NOT EDIT.
package client

import (
	"encoding/binary"
	model0 "example.org/gosvm/multi-state/model"
	"fmt"
)

const AccountVaultSize = 61
const AccountVaultVersion uint32 = 1

func EncodeAccountVault(v model0.Vault) []byte {
	b := make([]byte, 61)
	binary.LittleEndian.PutUint64(b, 2193914825299115253)
	for j := uint64(0); j < 32; j++ {
		b[8+j*1] = byte(v.Authority[j])
	}
	b[40] = byte(v.Audit.Tag)
	binary.LittleEndian.PutUint32(b[41:], uint32(v.Audit.Epoch))
	binary.LittleEndian.PutUint64(b[45:], uint64(v.Balance))
	binary.LittleEndian.PutUint64(b[53:], uint64(v.Moves))
	return b
}
func DecodeAccountVault(b []byte) (model0.Vault, error) {
	var v model0.Vault
	if len(b) != 61 {
		return v, fmt.Errorf("invalid AccountVault size")
	}
	if binary.LittleEndian.Uint64(b) != 2193914825299115253 {
		return v, fmt.Errorf("invalid AccountVault discriminator/version")
	}
	for j := uint64(0); j < 32; j++ {
		v.Authority[j] = byte(b[8+j*1])
	}
	v.Audit.Tag = byte(b[40])
	v.Audit.Epoch = uint32(binary.LittleEndian.Uint32(b[41:]))
	v.Balance = uint64(binary.LittleEndian.Uint64(b[45:]))
	v.Moves = uint64(binary.LittleEndian.Uint64(b[53:]))
	return v, nil
}

const AccountPolicySize = 48
const AccountPolicyVersion uint32 = 1

func EncodeAccountPolicy(v model0.Policy) []byte {
	b := make([]byte, 48)
	binary.LittleEndian.PutUint64(b, 5880542890593465198)
	for j := uint64(0); j < 32; j++ {
		b[8+j*1] = byte(v.Authority[j])
	}
	binary.LittleEndian.PutUint64(b[40:], uint64(v.Limit))
	return b
}
func DecodeAccountPolicy(b []byte) (model0.Policy, error) {
	var v model0.Policy
	if len(b) != 48 {
		return v, fmt.Errorf("invalid AccountPolicy size")
	}
	if binary.LittleEndian.Uint64(b) != 5880542890593465198 {
		return v, fmt.Errorf("invalid AccountPolicy discriminator/version")
	}
	for j := uint64(0); j < 32; j++ {
		v.Authority[j] = byte(b[8+j*1])
	}
	v.Limit = uint64(binary.LittleEndian.Uint64(b[40:]))
	return v, nil
}

const InstructionMoveSize = 16
const InstructionMoveVersion uint32 = 1

func EncodeInstructionMove(v model0.MoveArgs) []byte {
	b := make([]byte, 16)
	binary.LittleEndian.PutUint64(b, 17046868013462492629)
	binary.LittleEndian.PutUint64(b[8:], uint64(v.Amount))
	return b
}
func DecodeInstructionMove(b []byte) (model0.MoveArgs, error) {
	var v model0.MoveArgs
	if len(b) != 16 {
		return v, fmt.Errorf("invalid InstructionMove size")
	}
	if binary.LittleEndian.Uint64(b) != 17046868013462492629 {
		return v, fmt.Errorf("invalid InstructionMove discriminator/version")
	}
	v.Amount = uint64(binary.LittleEndian.Uint64(b[8:]))
	return v, nil
}

const InstructionSetLimitSize = 16
const InstructionSetLimitVersion uint32 = 1

func EncodeInstructionSetLimit(v model0.SetLimitArgs) []byte {
	b := make([]byte, 16)
	binary.LittleEndian.PutUint64(b, 15068491597679531006)
	binary.LittleEndian.PutUint64(b[8:], uint64(v.Limit))
	return b
}
func DecodeInstructionSetLimit(b []byte) (model0.SetLimitArgs, error) {
	var v model0.SetLimitArgs
	if len(b) != 16 {
		return v, fmt.Errorf("invalid InstructionSetLimit size")
	}
	if binary.LittleEndian.Uint64(b) != 15068491597679531006 {
		return v, fmt.Errorf("invalid InstructionSetLimit discriminator/version")
	}
	v.Limit = uint64(binary.LittleEndian.Uint64(b[8:]))
	return v, nil
}
