// Code generated by gosvm generate. DO NOT EDIT.
package client

import (
	"encoding/binary"
	program "example.com/typed-swap"
	"fmt"
)

func EncodePool(v program.Pool) []byte {
	b := make([]byte, 32)
	binary.LittleEndian.PutUint64(b, 13874821399147004193)
	binary.LittleEndian.PutUint64(b[8:], v.ReserveX)
	binary.LittleEndian.PutUint64(b[16:], v.ReserveY)
	binary.LittleEndian.PutUint64(b[24:], v.SwapCount)
	return b
}
func DecodePool(b []byte) (program.Pool, error) {
	var v program.Pool
	if len(b) != 32 {
		return v, fmt.Errorf("invalid Pool size")
	}
	if binary.LittleEndian.Uint64(b) != 13874821399147004193 {
		return v, fmt.Errorf("invalid Pool discriminator")
	}
	v.ReserveX = binary.LittleEndian.Uint64(b[8:])
	v.ReserveY = binary.LittleEndian.Uint64(b[16:])
	v.SwapCount = binary.LittleEndian.Uint64(b[24:])
	return v, nil
}
func EncodeSwapArgs(v program.SwapArgs) []byte {
	b := make([]byte, 24)
	binary.LittleEndian.PutUint64(b, 1704436820399925176)
	binary.LittleEndian.PutUint64(b[8:], v.AmountIn)
	binary.LittleEndian.PutUint64(b[16:], v.MinAmountOut)
	return b
}
func DecodeSwapArgs(b []byte) (program.SwapArgs, error) {
	var v program.SwapArgs
	if len(b) != 24 {
		return v, fmt.Errorf("invalid SwapArgs size")
	}
	if binary.LittleEndian.Uint64(b) != 1704436820399925176 {
		return v, fmt.Errorf("invalid SwapArgs discriminator")
	}
	v.AmountIn = binary.LittleEndian.Uint64(b[8:])
	v.MinAmountOut = binary.LittleEndian.Uint64(b[16:])
	return v, nil
}
