// Code generated by gosvm generate (schema 2). DO NOT EDIT.
package program

import (
	model0 "example.org/gosvm/multi-state/model"
	"gosvm/solana"
)

type GosvmAccountRef struct {
	Index uint64
	Key   [32]byte
}
type MoveAccounts struct {
	Source      model0.Vault
	Destination model0.Vault
	Policy      model0.Policy
	Authority   GosvmAccountRef
}
type SetLimitAccounts struct {
	Policy    model0.Policy
	Authority GosvmAccountRef
}

func gosvmRead(b []byte, off uint64, size uint64) uint64 {
	v := uint64(0)
	for j := uint64(0); j < size; j++ {
		v = v | uint64(b[off+j])<<(j*8)
	}
	return v
}
func gosvmWrite(b []byte, off uint64, size uint64, v uint64) {
	for j := uint64(0); j < size; j++ {
		b[off+j] = byte(v >> (j * 8))
	}
}
func gosvmKeysEqual(left []byte, right []byte) bool {
	if len(left) != 32 || len(right) != 32 {
		return false
	}
	for j := uint64(0); j < 32; j++ {
		if left[j] != right[j] {
			return false
		}
	}
	return true
}
func Process(c solana.Context) uint64 {
	ix := solana.Instruction(c)
	if len(ix) < 8 {
		return 6004
	}
	switch gosvmRead(ix, 0, 8) {
	case 17046868013462492629:
		if len(ix) != 16 {
			return 6004
		}
		return gosvmExecMove(c)
	case 15068491597679531006:
		if len(ix) != 16 {
			return 6004
		}
		return gosvmExecSetLimit(c)
	default:
		return 6004
	}
}
func gosvmExecMove(c solana.Context) uint64 {
	if solana.Count(c) != 4 {
		return 6000
	}
	if !solana.Writable(c, 0) {
		return 6001
	}
	if solana.Executable(c, 0) {
		return 6001
	}
	if !solana.Writable(c, 1) {
		return 6001
	}
	if solana.Executable(c, 1) {
		return 6001
	}
	if solana.Executable(c, 2) {
		return 6001
	}
	if !solana.Signer(c, 3) {
		return 6001
	}
	if solana.Executable(c, 3) {
		return 6001
	}
	id := solana.ProgramID(c)
	if len(id) != 32 {
		return 6002
	}
	key0 := solana.Key(c, 0)
	if len(key0) != 32 {
		return 6005
	}
	owner0 := solana.Owner(c, 0)
	if len(owner0) != 32 {
		return 6002
	}
	if !gosvmKeysEqual(owner0, id) {
		return 6002
	}
	key1 := solana.Key(c, 1)
	if len(key1) != 32 {
		return 6005
	}
	owner1 := solana.Owner(c, 1)
	if len(owner1) != 32 {
		return 6002
	}
	if !gosvmKeysEqual(owner1, id) {
		return 6002
	}
	key2 := solana.Key(c, 2)
	if len(key2) != 32 {
		return 6005
	}
	owner2 := solana.Owner(c, 2)
	if len(owner2) != 32 {
		return 6002
	}
	if !gosvmKeysEqual(owner2, id) {
		return 6002
	}
	key3 := solana.Key(c, 3)
	if len(key3) != 32 {
		return 6005
	}
	if gosvmKeysEqual(key0, key1) {
		return 6006
	}
	if gosvmKeysEqual(key0, key2) {
		return 6006
	}
	if gosvmKeysEqual(key0, key3) {
		return 6006
	}
	if gosvmKeysEqual(key1, key2) {
		return 6006
	}
	if gosvmKeysEqual(key1, key3) {
		return 6006
	}
	if gosvmKeysEqual(key2, key3) {
		return 6006
	}
	var accounts MoveAccounts
	state0 := solana.Data(c, 0)
	if len(state0) != 61 {
		return 6003
	}
	if gosvmRead(state0, 0, 8) != 2193914825299115253 {
		return 6003
	}
	for j := uint64(0); j < 32; j++ {
		accounts.Source.Authority[j] = byte(gosvmRead(state0, 8+j*1, 1))
	}
	accounts.Source.Audit.Tag = byte(gosvmRead(state0, 40, 1))
	accounts.Source.Audit.Epoch = uint32(gosvmRead(state0, 41, 4))
	accounts.Source.Balance = uint64(gosvmRead(state0, 45, 8))
	accounts.Source.Moves = uint64(gosvmRead(state0, 53, 8))
	state1 := solana.Data(c, 1)
	if len(state1) != 61 {
		return 6003
	}
	if gosvmRead(state1, 0, 8) != 2193914825299115253 {
		return 6003
	}
	for j := uint64(0); j < 32; j++ {
		accounts.Destination.Authority[j] = byte(gosvmRead(state1, 8+j*1, 1))
	}
	accounts.Destination.Audit.Tag = byte(gosvmRead(state1, 40, 1))
	accounts.Destination.Audit.Epoch = uint32(gosvmRead(state1, 41, 4))
	accounts.Destination.Balance = uint64(gosvmRead(state1, 45, 8))
	accounts.Destination.Moves = uint64(gosvmRead(state1, 53, 8))
	state2 := solana.Data(c, 2)
	if len(state2) != 48 {
		return 6003
	}
	if gosvmRead(state2, 0, 8) != 5880542890593465198 {
		return 6003
	}
	for j := uint64(0); j < 32; j++ {
		accounts.Policy.Authority[j] = byte(gosvmRead(state2, 8+j*1, 1))
	}
	accounts.Policy.Limit = uint64(gosvmRead(state2, 40, 8))
	accounts.Authority.Index = 3
	for j := uint64(0); j < 32; j++ {
		accounts.Authority.Key[j] = key3[j]
	}
	for j := uint64(0); j < 32; j++ {
		if accounts.Source.Authority[j] != key3[j] {
			return 6007
		}
	}
	for j := uint64(0); j < 32; j++ {
		if accounts.Destination.Authority[j] != key3[j] {
			return 6007
		}
	}
	ix := solana.Instruction(c)
	var args model0.MoveArgs
	args.Amount = uint64(gosvmRead(ix, 8, 8))
	updated, code := Move(c, accounts, args)
	if code != 0 {
		return code
	}
	for j := uint64(0); j < 32; j++ {
		gosvmWrite(state0, 8+j*1, 1, uint64(updated.Source.Authority[j]))
	}
	gosvmWrite(state0, 40, 1, uint64(updated.Source.Audit.Tag))
	gosvmWrite(state0, 41, 4, uint64(updated.Source.Audit.Epoch))
	gosvmWrite(state0, 45, 8, uint64(updated.Source.Balance))
	gosvmWrite(state0, 53, 8, uint64(updated.Source.Moves))
	for j := uint64(0); j < 32; j++ {
		gosvmWrite(state1, 8+j*1, 1, uint64(updated.Destination.Authority[j]))
	}
	gosvmWrite(state1, 40, 1, uint64(updated.Destination.Audit.Tag))
	gosvmWrite(state1, 41, 4, uint64(updated.Destination.Audit.Epoch))
	gosvmWrite(state1, 45, 8, uint64(updated.Destination.Balance))
	gosvmWrite(state1, 53, 8, uint64(updated.Destination.Moves))
	_ = updated
	return 0
}
func gosvmExecSetLimit(c solana.Context) uint64 {
	if solana.Count(c) != 2 {
		return 6000
	}
	if !solana.Writable(c, 0) {
		return 6001
	}
	if solana.Executable(c, 0) {
		return 6001
	}
	if !solana.Signer(c, 1) {
		return 6001
	}
	if solana.Executable(c, 1) {
		return 6001
	}
	id := solana.ProgramID(c)
	if len(id) != 32 {
		return 6002
	}
	key0 := solana.Key(c, 0)
	if len(key0) != 32 {
		return 6005
	}
	owner0 := solana.Owner(c, 0)
	if len(owner0) != 32 {
		return 6002
	}
	if !gosvmKeysEqual(owner0, id) {
		return 6002
	}
	key1 := solana.Key(c, 1)
	if len(key1) != 32 {
		return 6005
	}
	if gosvmKeysEqual(key0, key1) {
		return 6006
	}
	var accounts SetLimitAccounts
	state0 := solana.Data(c, 0)
	if len(state0) != 48 {
		return 6003
	}
	if gosvmRead(state0, 0, 8) != 5880542890593465198 {
		return 6003
	}
	for j := uint64(0); j < 32; j++ {
		accounts.Policy.Authority[j] = byte(gosvmRead(state0, 8+j*1, 1))
	}
	accounts.Policy.Limit = uint64(gosvmRead(state0, 40, 8))
	accounts.Authority.Index = 1
	for j := uint64(0); j < 32; j++ {
		accounts.Authority.Key[j] = key1[j]
	}
	for j := uint64(0); j < 32; j++ {
		if accounts.Policy.Authority[j] != key1[j] {
			return 6007
		}
	}
	ix := solana.Instruction(c)
	var args model0.SetLimitArgs
	args.Limit = uint64(gosvmRead(ix, 8, 8))
	updated, code := SetLimit(c, accounts, args)
	if code != 0 {
		return code
	}
	for j := uint64(0); j < 32; j++ {
		gosvmWrite(state0, 8+j*1, 1, uint64(updated.Policy.Authority[j]))
	}
	gosvmWrite(state0, 40, 8, uint64(updated.Policy.Limit))
	_ = updated
	return 0
}
