#!/usr/bin/env python3
"""Adapt the existing Go/lean Rust baselines to Anchor's identical token wire format.
No arithmetic, account validation, or CPI algorithm is changed.
"""
from pathlib import Path
import hashlib
ROOT=Path(__file__).resolve().parents[1]
def write(p,s):
 p=ROOT/p
 if not p.exists() or p.read_text()!=s:p.write_text(s)
def tag(s):return hashlib.sha256(s.encode()).digest()[:8]
def b58(b):
 alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';n=int.from_bytes(b,'big');out=''
 while n:n,r=divmod(n,58);out=alphabet[r]+out
 return '1'*(len(b)-len(b.lstrip(b'\0')))+out
pool=int.from_bytes(tag('account:Pool'),'little');ix=int.from_bytes(tag('global:swap'),'little')
s=(ROOT/'examples/tokenswap/swap.go').read_text()
s=s.replace('package tokenswap','package anchortoken')
s=s.replace('len(state) != 137 || len(ix) != 16','len(state) != 145 || len(ix) != 24')
s=s.replace('if !same32(solana.Owner',f'if load64(state,0)!={pool} || load64(ix,0)!={ix} {{return 102}}\n\tif !same32(solana.Owner',1)
s=s.replace('state, 129','state, 137').replace('state[128]','state[136]')
# Every state offset used by same32 shifts by the account discriminator size.
import re
s=re.sub(r'state, (0|32|64|96)(?=[,)])',lambda m:'state, '+str(int(m[1])+8),s)
s=s.replace('load64(ix, 8)','load64(ix, 16)').replace('load64(ix, 0)','load64(ix, 8)')
s='// Generated by scripts/anchor_prepare.py from the original token baseline.\n'+s
write('benchmarks/anchor/go-token/swap.go',s)
s=(ROOT/'baselines/tokenswap-rust/src/lib.rs').read_text()
s=s.replace('let state=a[0].data;let ix=c.instruction;', 'let state=a[0].data.add(8);let ix=c.instruction.add(8);')
s=s.replace('a[0].len!=137||c.len!=16','a[0].len!=145||c.len!=24')
s=s.replace('if !same(a[0].owner',f'if load(a[0].data)!={pool}||load(c.instruction)!={ix}{{return 102}}\n    if !same(a[0].owner',1)
write('benchmarks/anchor/lean-token/src/lib.rs','// Generated wire-format adaptation; core is unchanged.\n'+s)
s=(ROOT/'baselines/tokenswap-rust/Cargo.toml').read_text().replace('name = "tokenswap-rust"','name = "anchor-lean-token"')
write('benchmarks/anchor/lean-token/Cargo.toml',s)
p=ROOT/'benchmarks/anchor/token/src/lib.rs';s=p.read_text().replace('PROGRAM_ID',b58(hashlib.sha256(b'tokenswap Anchor').digest()));write(str(p.relative_to(ROOT)),s)
